services:
  db:
    image: postgres:14
    container_name: donate-app-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - donate-app-network

volumes:
  db-data:

networks:
  donate-app-network:
    driver: bridge
