version: '3.8'

services:
  db:
    image: postgres:14
    container_name: donate-app-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - donate-app-network

  backend:
    build: ./server
    container_name: donate-app-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: my_database
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - donate-app-network

  frontend:
    build: ./client
    container_name: donate-app-frontend
    ports:
      - "3000:3000"
    networks:
      - donate-app-network

volumes:
  db-data:

networks:
  donate-app-network:
    driver: bridge
